$combined = 'C:\Users\mohiq\VirtualBox VMs\CTI-Skripsi\06-Dashboard\cti-dashboard-v3-combined.ndjson'
$fieldsFile = 'C:\Users\mohiq\VirtualBox VMs\CTI-Skripsi\06-Dashboard\cti-fields.json'

# Attempt to read the fields JSON generated by the refresh script
$fieldsJsonString = $null
if (Test-Path $fieldsFile) {
    try {
        $fieldsContainer = Get-Content -Raw -Path $fieldsFile | ConvertFrom-Json -ErrorAction Stop
        if ($fieldsContainer.fields) {
            # The file contains a 'fields' property, so we extract its value and convert back to a JSON string
            $fieldsJsonString = $fieldsContainer.fields | ConvertTo-Json -Depth 50 -Compress
        }
    } catch {
        Write-Warning "Could not parse '$fieldsFile'. Will create dashboard with bare index-patterns. Run refresh script later."
    }
}

$attributes = @{ title = 'cti-logs-iqbal-*'; timeFieldName = '@timestamp' }
if ($fieldsJsonString) {
    $attributes['fields'] = $fieldsJsonString
}

$ip1 = @{ type = 'index-pattern'; id = '7afca9a4-6f1e-4e1c-81e0-b82fd03711b3'; attributes = $attributes } | ConvertTo-Json -Depth 10 -Compress
$ip2 = @{ type = 'index-pattern'; id = 'ba3ea9c0-2add-4700-b0e9-ebc444ef41ec'; attributes = $attributes } | ConvertTo-Json -Depth 10 -Compress

Set-Content -Path $combined -Value $ip1
Add-Content -Path $combined -Value $ip2

# Membaca file visualisasi dan otomatis memperbaiki error field source_ip_fixed -> source_ip_fixed.keyword
$vizContent = Get-Content -Raw -Path 'd:\skripsi josjis\eksperimen\cti-dashboard-v3-visualizations.ndjson'
$vizContent = $vizContent -replace 'source_ip_fixed(?!\.keyword)', 'source_ip_fixed.keyword'
$vizContent = $vizContent -replace 'source\.ip(?!\.keyword)', 'source.ip.keyword'
$vizContent = $vizContent -replace 'destination\.ip(?!\.keyword)', 'destination.ip.keyword'
$vizContent = $vizContent -replace 'src_ip(?!\.keyword)', 'src_ip.keyword'
$vizContent = $vizContent -replace 'dest_ip(?!\.keyword)', 'dest_ip.keyword'
$vizContent = $vizContent -replace 'alert\.signature(?!\.keyword)', 'alert.signature.keyword'
$vizContent = $vizContent -replace 'mitre\.tactic(?!\.keyword)', 'mitre.tactic.keyword'
$vizContent = $vizContent -replace 'mitre\.technique_name(?!\.keyword)', 'mitre.technique_name.keyword'
$vizContent = $vizContent -replace 'mitre\.technique_id(?!\.keyword)', 'mitre.technique_id.keyword'
$vizContent = $vizContent -replace 'pyramid\.layer(?!\.keyword)', 'pyramid.layer.keyword'
$vizContent = $vizContent -replace 'source_ip(?!\.keyword|_fixed)', 'source_ip_fixed.keyword'
Add-Content -Path $combined -Value $vizContent

# Membaca file panel validasi dan otomatis memperbaiki error field source_ip_fixed -> source_ip_fixed.keyword
$valContent = Get-Content -Raw -Path 'd:\skripsi josjis\eksperimen\cti-dashboard-v3-validation-panels.ndjson'
$valContent = $valContent -replace 'source_ip_fixed(?!\.keyword)', 'source_ip_fixed.keyword'
$valContent = $valContent -replace 'source\.ip(?!\.keyword)', 'source.ip.keyword'
$valContent = $valContent -replace 'alert\.signature(?!\.keyword)', 'alert.signature.keyword'
$valContent = $valContent -replace 'mitre\.technique_id(?!\.keyword)', 'mitre.technique_id.keyword'
Add-Content -Path $combined -Value $valContent

$panels = '[{"panelIndex":"1","gridData":{"x":0,"y":0,"w":24,"h":6,"i":"1"},"embeddableConfig":{},"panelRefName":"panel_0"},{"panelIndex":"2","gridData":{"x":24,"y":0,"w":24,"h":6,"i":"2"},"embeddableConfig":{},"panelRefName":"panel_1"},{"panelIndex":"3","gridData":{"x":0,"y":6,"w":12,"h":4,"i":"3"},"embeddableConfig":{},"panelRefName":"panel_2"},{"panelIndex":"4","gridData":{"x":12,"y":6,"w":12,"h":4,"i":"4"},"embeddableConfig":{},"panelRefName":"panel_3"},{"panelIndex":"5","gridData":{"x":0,"y":10,"w":12,"h":6,"i":"5"},"embeddableConfig":{},"panelRefName":"panel_4"},{"panelIndex":"6","gridData":{"x":12,"y":10,"w":12,"h":6,"i":"6"},"embeddableConfig":{},"panelRefName":"panel_5"},{"panelIndex":"7","gridData":{"x":0,"y":16,"w":8,"h":4,"i":"7"},"embeddableConfig":{},"panelRefName":"panel_6"},{"panelIndex":"8","gridData":{"x":8,"y":16,"w":8,"h":4,"i":"8"},"embeddableConfig":{},"panelRefName":"panel_7"},{"panelIndex":"9","gridData":{"x":16,"y":16,"w":8,"h":4,"i":"9"},"embeddableConfig":{},"panelRefName":"panel_8"}]'
$dashboard = @{
  type = 'dashboard'
  id = 'v3-cti-dashboard-final'
  attributes = @{
    title = 'CTI Dashboard V3'
    description = 'Visibilitas MITRE - CTI Skripsi'
    panelsJSON = $panels
    optionsJSON = '{"useMargins":true,"hidePanelTitles":false}'
    kibanaSavedObjectMeta = @{ searchSourceJSON = '{"query":{"query":"","language":"kuery"},"filter":[]}' }
  }
  references = @(
    @{ name = 'kibanaSavedObjectMeta.searchSourceJSON.index'; type = 'index-pattern'; id = '7afca9a4-6f1e-4e1c-81e0-b82fd03711b3' }
    @{ name = 'panel_0'; type = 'visualization'; id = 'v3-mitre-mapped-count' }
    @{ name = 'panel_1'; type = 'visualization'; id = 'v3-mitre-technique-pie' }
    @{ name = 'panel_2'; type = 'visualization'; id = 'v3-mitre-tactic-bar' }
    @{ name = 'panel_3'; type = 'visualization'; id = 'v3-mitre-timeline' }
    @{ name = 'panel_4'; type = 'visualization'; id = 'v3-pyramid-layer-bar' }
    @{ name = 'panel_5'; type = 'visualization'; id = 'v3-threat-actors-table' }
    @{ name = 'panel_6'; type = 'visualization'; id = 'v3-validation-nmap' }
    @{ name = 'panel_7'; type = 'visualization'; id = 'v3-validation-hydra' }
    @{ name = 'panel_8'; type = 'visualization'; id = 'v3-validation-nikto' }
  )
}
$line = $dashboard | ConvertTo-Json -Compress -Depth 10
Add-Content -Path $combined -Value $line
Write-Output "Combined NDJSON created at $combined; size: $(Get-Item $combined).Length"
