filter {
  if [data][alert][signature_id] {
    mutate { add_field => { "[@metadata][sig_id_str]" => "%{[data][alert][signature_id]}" } }
  } else if [alert][signature_id] {
    mutate { add_field => { "[@metadata][sig_id_str]" => "%{[alert][signature_id]}" } }
  } else if [suricata][eve][alert][signature_id] {
    mutate { add_field => { "[@metadata][sig_id_str]" => "%{[suricata][eve][alert][signature_id]}" } }
  } else if [wazuh][data][alert][signature_id] {
    mutate { add_field => { "[@metadata][sig_id_str]" => "%{[wazuh][data][alert][signature_id]}" } }
  }

  if [@metadata][sig_id_str] {
    translate {
      source => "[@metadata][sig_id_str]"
      target => "[mitre][technique_id]"
      dictionary_path => "/etc/logstash/dictionaries/mitre-mapping.yml"
      fallback => "Unmapped"
    }

    translate {
      source => "[mitre][technique_id]"
      target => "[mitre][technique_name]"
      dictionary_path => "/etc/logstash/dictionaries/mitre-id-to-name.yml"
      fallback => "Unmapped"
    }
  }
}
